### ISSUE TITLE
Set up Firebase, and connect application.

### ISSUE THREAD

**Issue by MatthewSloyan** [MatthewSloyan/IT-Professional-Skills-Group-Project#2]
I need to create a Firebase, set up a node.js server and connect to the application to allow users to upload and save their files.

**Comment by MatthewSloyan** [comment]
I've initialized the database and set up a test collection.

![image](https://user-images.githubusercontent.com/26766108/52905066-75ee1d80-322c-11e9-83fa-ecb64371cca7.png)

**Comment by kevinniland** [comment]
server.js file created with database connection. Needs testing.
![capture1](https://user-images.githubusercontent.com/26802466/53090184-9527cc00-3506-11e9-953a-36a4fe870462.PNG)

**Comment by MatthewSloyan** [comment]
I have added Express to the server to allow HTTP requests, and added basic Firebase functionality for uploading a file.

However when running the server file it can't find the "serviceAccountKey.json" credentials file. Will create issue.

**Comment by MatthewSloyan** [comment]
However when running the server file it can't find the "serviceAccountKey.json" credentials file. Will create issue.

**Comment by MatthewSloyan** [comment]
From research we have found that using Firebase with Node JS was depreciated and the focus is now on using Google Cloud for storage. With that in mind I began to use Google Cloud instead to save the files. I will create further issues to document my progress and advancements.
