### ISSUE TITLE
Ionic styling not being applied on certain elements

### ISSUE THREAD

**Issue by kevinniland** [MatthewSloyan/IT-Professional-Skills-Group-Project#4]
Ionic styling is not being applied to certain elements, such as button. For example, the buttons located on the register.page.html are appearing as plain, grey buttons.

**Comment by MatthewSloyan** [comment]
Fixed issue by updating to ion-button, as the documentation changed. It now displays the correctly styled buttons. However the layout and design will be improved towards the end of the project.

![image](https://user-images.githubusercontent.com/26766108/53286036-4a08f580-3760-11e9-8006-e421ba2e6746.png)

![image](https://user-images.githubusercontent.com/26766108/53286049-8fc5be00-3760-11e9-9df6-fa30692edee0.png)
