### ISSUE TITLE
Routing between Register and Login page via button click

### ISSUE THREAD

**Issue by kevinniland** [MatthewSloyan/IT-Professional-Skills-Group-Project#6]
NavController issue - no provider

**Comment by MatthewSloyan** [comment]
From research I found that routing with buttons can be easily handled through HTML with a [routerLink] tag. In light of this I have updated both the buttons on the Register and Login page to fix this. The user can now route between the login and register page.

![image](https://user-images.githubusercontent.com/26766108/53286098-24c8b700-3761-11e9-8231-52a4bd01d261.png)
